### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nmschulte** [981213/ch347-nor-prog#1]
Hi, I wonder how you license this code if at all?  Similarly w/ your [spi-nand-prog](https://github.com/981213/spi-nand-prog) code.  Thanks.

**Comment by 981213** [comment]
I decided to put the CH347 driver I wrote under BSD license as the file comment said.
Other code are taken from other projects. Specifically, the SPI-NOR programmer code in this project comes from https://github.com/hackpascal/ch341prog where @hackpascal said he puts it in public domain. The spi-nand code in spi-nand-prog is taken from Linux, so it is under GPLv2.

**Comment by nmschulte** [comment]
Oh I see it now: https://github.com/981213/ch347-nor-prog/blob/master/ch347.c#L1

Thank you!
